@baseurl = http://localhost:4004/odata/v4/productshop



#GET {{baseurl}}/addition(num1=5,num2=10)

#GET {{baseurl}}/printhelloworld(name= "Hello")
#GET {{baseurl}}/Myfunction(category =2)
#GET {{baseurl}}/Supplier
#GET {{baseurl}}/Product
# POST to add 1 more set in the existing record eg product


POST {{baseurl}}/Product
Headers:
  Content-Type: application/json

{
  "name": "Rum",
  "Carrier": "AIR1",
  "Labelflag": "ZZ",
  "Category": 10,
  "Newfield_price": 900,
  "Newfield_stock": 90
}