@baseurl = http://localhost:4004/odata/v4/productshop



#GET {{baseurl}}/addition(num1=5,num2=10)

#GET {{baseurl}}/printhelloworld(name= "Hello")
#GET {{baseurl}}/Myfunction(category =2)
#GET {{baseurl}}/Supplier
#GET {{baseurl}}/Product
# POST to add 1 more set in the existing record eg product


#POST {{baseurl}}/Product
#Headers:
 # Content-Type: application/json

#{
  #"name": "Philips",
  #"Carrier": "AIR2",
  #"Labelflag": "RB",
  #"Category": 12,
  #"Newfield_price": 1900,
  #"Newfield_stock": 100
#}

#GET {{baseurl}}/Product?$expand=Supplier #expand command is to open the linkage between entities


#GET {{baseurl}}/Product?$expand=Category,Supplier
#GET  {{baseurl}}/Product?$expand=supplier&$select=name,Category

#GET  {{baseurl}}/Supplier?$expand=products

GET {{baseurl}}/Product?$expand=conversation